name: build-examples

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x, 22.x, 23.x, 24.x, 25.x] # bfj@8.0.0: The engine "node" is incompatible with this module. Expected version ">= 18.0.0".

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v5
        with:
          version: 8

      - name: Pnpm install
        run: pnpm install --no-frozen-lockfile

      - name: Build copy
        working-directory: ./packages/copy
        run: |
          pnpm run build
        env:
          CI: false

      # - name: Build ./examples/cra-app-react16
      #   working-directory: ./examples/cra-app-react16
      #   run: |
      #     pnpm run build
      #   env:
      #     CI: false

      - name: Build ./examples/cra-app-react18
        working-directory: ./examples/cra-app-react18
        run: |
          pnpm run test
          pnpm run build
        env:
          CI: false

      - name: Build ./examples/cra-app-react19
        working-directory: ./examples/cra-app-react19
        run: |
          pnpm run test
          pnpm run build
        env:
          CI: false

      - name: Build ./examples/with-vite-react18
        working-directory: ./examples/with-vite-react18
        run: |
          pnpm run test
          pnpm run build
        env:
          CI: false

      - name: Build ./examples/with-vite-react19
        working-directory: ./examples/with-vite-react19
        run: |
          pnpm run test
          pnpm run build
        env:
          CI: false
