name: build-examples-old

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x] # The engine "node" is incompatible with this module. Expected version ">=16".

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v5
        with:
          version: 7

      - name: Pnpm install
        run: pnpm install --no-frozen-lockfile

      - name: Build copy
        working-directory: ./packages/copy
        run: |
          pnpm run build
        env:
          CI: false

      - name: Build ./examples/cra-app-react16
        working-directory: ./examples/cra-app-react16
        run: |
          yarn install
          yarn run build
        env:
          CI: false

      - name: Build ./examples/cra-app-react16
        working-directory: ./examples/cra-app-react17
        run: |
          yarn install
          yarn run build
        env:
          CI: false
